name: saucectl playwright tests

on:
  pull_request:
  push:
    branches:
      - develop
  schedule: 
    - cron: '0 22 * * *'

env:
  SAUCE_USERNAME: 'Hazim'
  SAUCE_ACCESS_KEY: 'b545b3eb-c537-47e1-bc7c-4c1462cc21eb'
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Saucectl RUN
        uses: saucectl run "@regression"
        with:
          concurrency: 1

      - name: Saucectl RUN Send Email
        uses: saucectl run "@sendEmail"
        with:
          concurrency: 1    