apiVersion: v1alpha
kind: playwright
sauce:
  region: us-west-1
  concurrency: 1 # Controls how many suites are executed at the same time.
  metadata:
    tags:
      - e2e
      - release team
      - other tag
npm:
  packages:
    nodemailer: "^6.9.14"
    lru-cache: "10.2.2"
    glob: "10.4.2"
    rimraf: "5.0.7"
    @eslint/config-array: "0.16.0"
    @eslint/object-schema: "2.1.4"
playwright:
  version: package.json # See https://docs.saucelabs.com/web-apps/automated-testing/playwright/#supported-testing-platforms for a list of supported versions.
  configFile: playwright.config.js
rootDir: ./
suites:
  - name: "Regression"
    platformName: "Windows 11"
    screenResolution: "1440x900"
    testMatch: ['.*.js']
    params:
      browserName: "firefox"
      project: "Regression"
