apiVersion: v1alpha
kind: playwright
sauce:
  region: us-west-1
  concurrency: 1 # Controls how many suites are executed at the same time.
  metadata:
    tags:
      - e2e
      - release team
      - other tag
npm:
  packages:
    nodemailer: "6.9.14"
playwright:
  version: package.json # See https://docs.saucelabs.com/web-apps/automated-testing/playwright/#supported-testing-platforms for a list of supported versions.
  configFile: playwright.config.js
rootDir: ./
suites:
  - name: "Regression"
    platformName: "Windows 11"
    screenResolution: "1440x900"
    testMatch: ['.*.js']
    params:
      browserName: "firefox"
      project: "Regression"
  - name: "Sender"
    platformName: "Windows 11"
    screenResolution: "1440x900"
    testMatch: ['.*.js']
    params:
      browserName: "firefox"
      project: "Sender"
# Controls what artifacts to fetch when the suites have finished.
# artifacts:
#   download:
#     when: always
#     match:
#       - console.log
#     directory: ./artifacts/
